#!/bin/bash
plumed patch -p <<!
2
!
mkdir build
cd build
#export DYLD_LIBRARY_PATH=/opt/MacOSX10.9.sdk/usr/lib/system/:$DYLD_LIBRARY_PATH
export MACOSX_DEPLOYMENT_TARGET=10.9 # - helps on some OSX platforms
## See INSTALL of gromacs distro
cmake .. \
  -DGMX_BUILD_MDRUN_ONLY=ON \
  -DSHARED_LIBS_DEFAULT=OFF \
  -DBUILD_SHARED_LIBS=OFF \
  -DGMX_PREFER_STATIC_LIBS=YES \
  -DGMX_BUILD_OWN_FFTW=ON \
  -DGMX_DEFAULT_SUFFIX=ON \
  -DREGRESSIONTEST_DOWNLOAD=ON \
  -DGMX_MPI=ON \
  -DGMX_GPU=OFF \
  -DGMX_SIMD=SSE2 \
  -DGMX_USE_OPENCL=OFF \
  -DCMAKE_PREFIX_PATH=$PREFIX \
  -DGMX_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_OSX_SYSROOT=/opt/MacOSX10.9.sdk/ \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
#make -j 8
make
make check
make install
make clean

cmake .. \
  -DGMX_BUILD_MDRUN_ONLY=OFF \
  -DSHARED_LIBS_DEFAULT=OFF \
  -DBUILD_SHARED_LIBS=OFF \
  -DGMX_PREFER_STATIC_LIBS=YES \
  -DGMX_BUILD_OWN_FFTW=ON \
  -DGMX_DEFAULT_SUFFIX=ON \
  -DREGRESSIONTEST_DOWNLOAD=ON \
  -DGMX_MPI=OFF \
  -DGMX_GPU=OFF \
  -DGMX_SIMD=SSE2 \
  -DGMX_USE_OPENCL=OFF \
  -DCMAKE_PREFIX_PATH=$PREFIX \
  -DGMX_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_OSX_SYSROOT=/opt/MacOSX10.9.sdk/ \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
#make -j 8
make
make check
make install
